#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCulQ4Ao8ZwdkzNi8A/Mhd0HRw964W94ftW6CCnKiHDj5ImovnakMge7RphvC8wLOmFY4c532hEJIW/LCVsd6Ix1LG5I61gJhnl/aJ/nyFFN2A05qleGEc95JtMND/+Cao02uffl6W6hvUv7m7Gc6UN2QOT7JAHssul3jQRQm4K6DEC6JtoMLg1Hu6q8XDKZqWl8CiJHeubWJzpplQBq2q7sCCuwEiDP5RC8jiuG3zHtBiFskVdKUUDJhWNis+2/3VUAk1petCvD1CS1lKl/FXAbR3i5SuS9Ew8OaSUTp/fX88i1iPpxAKXcJc36hqWmmMbTAPpM2Rx0h/qiw1SkpZh hpereira@ni-84597-0
coreos:
  units:
  - name: nginx.service
    command: start
    enable: true
    content: |
      [Install]
      WantedBy=multi-user.target
      
      [Unit]
      Description=nginx
      After=docker.service
      After=nginx.service
      Wants=docker.service
      
      [Service]
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker rm nginx
      ExecStart=/usr/bin/docker run \
                --name nginx \
                --net host \
                nginx:1.14.2-alpine
      ExecStop=/usr/bin/docker stop nginx
      ExecStopPost=/usr/bin/docker rm nginx